//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Inventory.Report {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ReportDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ReportDataSet : global::System.Data.DataSet {
        
        private Chi_Tiet_Phieu_Nhap_Vat_TuDataTable tableChi_Tiet_Phieu_Nhap_Vat_Tu;
        
        private Phieu_Nhap_KhoDataTable tablePhieu_Nhap_Kho;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public ReportDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected ReportDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Chi_Tiet_Phieu_Nhap_Vat_Tu"] != null)) {
                    base.Tables.Add(new Chi_Tiet_Phieu_Nhap_Vat_TuDataTable(ds.Tables["Chi_Tiet_Phieu_Nhap_Vat_Tu"]));
                }
                if ((ds.Tables["Phieu_Nhap_Kho"] != null)) {
                    base.Tables.Add(new Phieu_Nhap_KhoDataTable(ds.Tables["Phieu_Nhap_Kho"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Chi_Tiet_Phieu_Nhap_Vat_TuDataTable Chi_Tiet_Phieu_Nhap_Vat_Tu {
            get {
                return this.tableChi_Tiet_Phieu_Nhap_Vat_Tu;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Phieu_Nhap_KhoDataTable Phieu_Nhap_Kho {
            get {
                return this.tablePhieu_Nhap_Kho;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ReportDataSet cln = ((ReportDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Chi_Tiet_Phieu_Nhap_Vat_Tu"] != null)) {
                    base.Tables.Add(new Chi_Tiet_Phieu_Nhap_Vat_TuDataTable(ds.Tables["Chi_Tiet_Phieu_Nhap_Vat_Tu"]));
                }
                if ((ds.Tables["Phieu_Nhap_Kho"] != null)) {
                    base.Tables.Add(new Phieu_Nhap_KhoDataTable(ds.Tables["Phieu_Nhap_Kho"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableChi_Tiet_Phieu_Nhap_Vat_Tu = ((Chi_Tiet_Phieu_Nhap_Vat_TuDataTable)(base.Tables["Chi_Tiet_Phieu_Nhap_Vat_Tu"]));
            if ((initTable == true)) {
                if ((this.tableChi_Tiet_Phieu_Nhap_Vat_Tu != null)) {
                    this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.InitVars();
                }
            }
            this.tablePhieu_Nhap_Kho = ((Phieu_Nhap_KhoDataTable)(base.Tables["Phieu_Nhap_Kho"]));
            if ((initTable == true)) {
                if ((this.tablePhieu_Nhap_Kho != null)) {
                    this.tablePhieu_Nhap_Kho.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ReportDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ReportDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableChi_Tiet_Phieu_Nhap_Vat_Tu = new Chi_Tiet_Phieu_Nhap_Vat_TuDataTable();
            base.Tables.Add(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu);
            this.tablePhieu_Nhap_Kho = new Phieu_Nhap_KhoDataTable();
            base.Tables.Add(this.tablePhieu_Nhap_Kho);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeChi_Tiet_Phieu_Nhap_Vat_Tu() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializePhieu_Nhap_Kho() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ReportDataSet ds = new ReportDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEventHandler(object sender, Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent e);
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void Phieu_Nhap_KhoRowChangeEventHandler(object sender, Phieu_Nhap_KhoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Chi_Tiet_Phieu_Nhap_Vat_TuDataTable : global::System.Data.TypedTableBase<Chi_Tiet_Phieu_Nhap_Vat_TuRow> {
            
            private global::System.Data.DataColumn columnStt;
            
            private global::System.Data.DataColumn columnMa_vat_tu;
            
            private global::System.Data.DataColumn columnTen_vat_tu;
            
            private global::System.Data.DataColumn columnChat_luong;
            
            private global::System.Data.DataColumn columnTen_don_vi_tinh;
            
            private global::System.Data.DataColumn columnSo_luong_yeu_cau;
            
            private global::System.Data.DataColumn columnSo_luong_thuc_lanh;
            
            private global::System.Data.DataColumn columnDon_gia;
            
            private global::System.Data.DataColumn columnThanh_tien;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuDataTable() {
                this.TableName = "Chi_Tiet_Phieu_Nhap_Vat_Tu";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Chi_Tiet_Phieu_Nhap_Vat_TuDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected Chi_Tiet_Phieu_Nhap_Vat_TuDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SttColumn {
                get {
                    return this.columnStt;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ma_vat_tuColumn {
                get {
                    return this.columnMa_vat_tu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ten_vat_tuColumn {
                get {
                    return this.columnTen_vat_tu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Chat_luongColumn {
                get {
                    return this.columnChat_luong;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ten_don_vi_tinhColumn {
                get {
                    return this.columnTen_don_vi_tinh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn So_luong_yeu_cauColumn {
                get {
                    return this.columnSo_luong_yeu_cau;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn So_luong_thuc_lanhColumn {
                get {
                    return this.columnSo_luong_thuc_lanh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Don_giaColumn {
                get {
                    return this.columnDon_gia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Thanh_tienColumn {
                get {
                    return this.columnThanh_tien;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuRow this[int index] {
                get {
                    return ((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEventHandler Chi_Tiet_Phieu_Nhap_Vat_TuRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEventHandler Chi_Tiet_Phieu_Nhap_Vat_TuRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEventHandler Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEventHandler Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddChi_Tiet_Phieu_Nhap_Vat_TuRow(Chi_Tiet_Phieu_Nhap_Vat_TuRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuRow AddChi_Tiet_Phieu_Nhap_Vat_TuRow(string Ma_vat_tu, string Ten_vat_tu, string Chat_luong, string Ten_don_vi_tinh, int So_luong_yeu_cau, int So_luong_thuc_lanh, int Don_gia, int Thanh_tien) {
                Chi_Tiet_Phieu_Nhap_Vat_TuRow rowChi_Tiet_Phieu_Nhap_Vat_TuRow = ((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        Ma_vat_tu,
                        Ten_vat_tu,
                        Chat_luong,
                        Ten_don_vi_tinh,
                        So_luong_yeu_cau,
                        So_luong_thuc_lanh,
                        Don_gia,
                        Thanh_tien};
                rowChi_Tiet_Phieu_Nhap_Vat_TuRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowChi_Tiet_Phieu_Nhap_Vat_TuRow);
                return rowChi_Tiet_Phieu_Nhap_Vat_TuRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                Chi_Tiet_Phieu_Nhap_Vat_TuDataTable cln = ((Chi_Tiet_Phieu_Nhap_Vat_TuDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Chi_Tiet_Phieu_Nhap_Vat_TuDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnStt = base.Columns["Stt"];
                this.columnMa_vat_tu = base.Columns["Ma_vat_tu"];
                this.columnTen_vat_tu = base.Columns["Ten_vat_tu"];
                this.columnChat_luong = base.Columns["Chat_luong"];
                this.columnTen_don_vi_tinh = base.Columns["Ten_don_vi_tinh"];
                this.columnSo_luong_yeu_cau = base.Columns["So_luong_yeu_cau"];
                this.columnSo_luong_thuc_lanh = base.Columns["So_luong_thuc_lanh"];
                this.columnDon_gia = base.Columns["Don_gia"];
                this.columnThanh_tien = base.Columns["Thanh_tien"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnStt = new global::System.Data.DataColumn("Stt", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStt);
                this.columnMa_vat_tu = new global::System.Data.DataColumn("Ma_vat_tu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_vat_tu);
                this.columnTen_vat_tu = new global::System.Data.DataColumn("Ten_vat_tu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTen_vat_tu);
                this.columnChat_luong = new global::System.Data.DataColumn("Chat_luong", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChat_luong);
                this.columnTen_don_vi_tinh = new global::System.Data.DataColumn("Ten_don_vi_tinh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTen_don_vi_tinh);
                this.columnSo_luong_yeu_cau = new global::System.Data.DataColumn("So_luong_yeu_cau", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSo_luong_yeu_cau);
                this.columnSo_luong_thuc_lanh = new global::System.Data.DataColumn("So_luong_thuc_lanh", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSo_luong_thuc_lanh);
                this.columnDon_gia = new global::System.Data.DataColumn("Don_gia", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDon_gia);
                this.columnThanh_tien = new global::System.Data.DataColumn("Thanh_tien", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThanh_tien);
                this.columnStt.AutoIncrement = true;
                this.columnStt.AutoIncrementSeed = 1;
                this.columnMa_vat_tu.Caption = "Mã vật tư";
                this.columnTen_vat_tu.Caption = "Tên, nhãn hiệu qui cách vật tư";
                this.columnChat_luong.Caption = "Chất lượng";
                this.columnTen_don_vi_tinh.Caption = "Đvt";
                this.columnSo_luong_yeu_cau.Caption = "Yêu cầu";
                this.columnSo_luong_thuc_lanh.Caption = "Thực nhập";
                this.columnDon_gia.Caption = "Đơn giá";
                this.columnThanh_tien.Caption = "Thành tiền";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuRow NewChi_Tiet_Phieu_Nhap_Vat_TuRow() {
                return ((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Chi_Tiet_Phieu_Nhap_Vat_TuRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(Chi_Tiet_Phieu_Nhap_Vat_TuRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Chi_Tiet_Phieu_Nhap_Vat_TuRowChanged != null)) {
                    this.Chi_Tiet_Phieu_Nhap_Vat_TuRowChanged(this, new Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent(((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Chi_Tiet_Phieu_Nhap_Vat_TuRowChanging != null)) {
                    this.Chi_Tiet_Phieu_Nhap_Vat_TuRowChanging(this, new Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent(((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleted != null)) {
                    this.Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleted(this, new Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent(((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleting != null)) {
                    this.Chi_Tiet_Phieu_Nhap_Vat_TuRowDeleting(this, new Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent(((Chi_Tiet_Phieu_Nhap_Vat_TuRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveChi_Tiet_Phieu_Nhap_Vat_TuRow(Chi_Tiet_Phieu_Nhap_Vat_TuRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ReportDataSet ds = new ReportDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Chi_Tiet_Phieu_Nhap_Vat_TuDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Phieu_Nhap_KhoDataTable : global::System.Data.TypedTableBase<Phieu_Nhap_KhoRow> {
            
            private global::System.Data.DataColumn columnTen_kho;
            
            private global::System.Data.DataColumn columnNgay_lap;
            
            private global::System.Data.DataColumn columnLy_do;
            
            private global::System.Data.DataColumn columnSo_hoa_don;
            
            private global::System.Data.DataColumn columnCong_trinh;
            
            private global::System.Data.DataColumn columnDia_Chi;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoDataTable() {
                this.TableName = "Phieu_Nhap_Kho";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Phieu_Nhap_KhoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected Phieu_Nhap_KhoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ten_khoColumn {
                get {
                    return this.columnTen_kho;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ngay_lapColumn {
                get {
                    return this.columnNgay_lap;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ly_doColumn {
                get {
                    return this.columnLy_do;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn So_hoa_donColumn {
                get {
                    return this.columnSo_hoa_don;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cong_trinhColumn {
                get {
                    return this.columnCong_trinh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Dia_ChiColumn {
                get {
                    return this.columnDia_Chi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoRow this[int index] {
                get {
                    return ((Phieu_Nhap_KhoRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Phieu_Nhap_KhoRowChangeEventHandler Phieu_Nhap_KhoRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Phieu_Nhap_KhoRowChangeEventHandler Phieu_Nhap_KhoRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Phieu_Nhap_KhoRowChangeEventHandler Phieu_Nhap_KhoRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event Phieu_Nhap_KhoRowChangeEventHandler Phieu_Nhap_KhoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddPhieu_Nhap_KhoRow(Phieu_Nhap_KhoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoRow AddPhieu_Nhap_KhoRow(string Ten_kho, System.DateTime Ngay_lap, string Ly_do, string So_hoa_don, string Cong_trinh, string Dia_Chi) {
                Phieu_Nhap_KhoRow rowPhieu_Nhap_KhoRow = ((Phieu_Nhap_KhoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Ten_kho,
                        Ngay_lap,
                        Ly_do,
                        So_hoa_don,
                        Cong_trinh,
                        Dia_Chi};
                rowPhieu_Nhap_KhoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPhieu_Nhap_KhoRow);
                return rowPhieu_Nhap_KhoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                Phieu_Nhap_KhoDataTable cln = ((Phieu_Nhap_KhoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Phieu_Nhap_KhoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnTen_kho = base.Columns["Ten_kho"];
                this.columnNgay_lap = base.Columns["Ngay_lap"];
                this.columnLy_do = base.Columns["Ly_do"];
                this.columnSo_hoa_don = base.Columns["So_hoa_don"];
                this.columnCong_trinh = base.Columns["Cong_trinh"];
                this.columnDia_Chi = base.Columns["Dia_Chi"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnTen_kho = new global::System.Data.DataColumn("Ten_kho", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTen_kho);
                this.columnNgay_lap = new global::System.Data.DataColumn("Ngay_lap", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNgay_lap);
                this.columnLy_do = new global::System.Data.DataColumn("Ly_do", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLy_do);
                this.columnSo_hoa_don = new global::System.Data.DataColumn("So_hoa_don", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSo_hoa_don);
                this.columnCong_trinh = new global::System.Data.DataColumn("Cong_trinh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCong_trinh);
                this.columnDia_Chi = new global::System.Data.DataColumn("Dia_Chi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDia_Chi);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoRow NewPhieu_Nhap_KhoRow() {
                return ((Phieu_Nhap_KhoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Phieu_Nhap_KhoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(Phieu_Nhap_KhoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Phieu_Nhap_KhoRowChanged != null)) {
                    this.Phieu_Nhap_KhoRowChanged(this, new Phieu_Nhap_KhoRowChangeEvent(((Phieu_Nhap_KhoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Phieu_Nhap_KhoRowChanging != null)) {
                    this.Phieu_Nhap_KhoRowChanging(this, new Phieu_Nhap_KhoRowChangeEvent(((Phieu_Nhap_KhoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Phieu_Nhap_KhoRowDeleted != null)) {
                    this.Phieu_Nhap_KhoRowDeleted(this, new Phieu_Nhap_KhoRowChangeEvent(((Phieu_Nhap_KhoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Phieu_Nhap_KhoRowDeleting != null)) {
                    this.Phieu_Nhap_KhoRowDeleting(this, new Phieu_Nhap_KhoRowChangeEvent(((Phieu_Nhap_KhoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovePhieu_Nhap_KhoRow(Phieu_Nhap_KhoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ReportDataSet ds = new ReportDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Phieu_Nhap_KhoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class Chi_Tiet_Phieu_Nhap_Vat_TuRow : global::System.Data.DataRow {
            
            private Chi_Tiet_Phieu_Nhap_Vat_TuDataTable tableChi_Tiet_Phieu_Nhap_Vat_Tu;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Chi_Tiet_Phieu_Nhap_Vat_TuRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableChi_Tiet_Phieu_Nhap_Vat_Tu = ((Chi_Tiet_Phieu_Nhap_Vat_TuDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Stt {
                get {
                    try {
                        return ((int)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.SttColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Stt\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.SttColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ma_vat_tu {
                get {
                    try {
                        return ((string)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_vat_tu\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ten_vat_tu {
                get {
                    try {
                        return ((string)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_vat_tuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ten_vat_tu\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_vat_tuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Chat_luong {
                get {
                    try {
                        return ((string)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luongColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Chat_luong\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luongColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ten_don_vi_tinh {
                get {
                    try {
                        return ((string)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_don_vi_tinhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ten_don_vi_tinh\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_don_vi_tinhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int So_luong_yeu_cau {
                get {
                    try {
                        return ((int)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cauColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'So_luong_yeu_cau\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cauColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int So_luong_thuc_lanh {
                get {
                    try {
                        return ((int)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'So_luong_thuc_lanh\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Don_gia {
                get {
                    try {
                        return ((int)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Don_giaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Don_gia\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Don_giaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Thanh_tien {
                get {
                    try {
                        return ((int)(this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tienColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Thanh_tien\' in table \'Chi_Tiet_Phieu_Nhap_Vat_Tu\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tienColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSttNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.SttColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSttNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.SttColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMa_vat_tuNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMa_vat_tuNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTen_vat_tuNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_vat_tuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTen_vat_tuNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_vat_tuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsChat_luongNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luongColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetChat_luongNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luongColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTen_don_vi_tinhNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_don_vi_tinhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTen_don_vi_tinhNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Ten_don_vi_tinhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSo_luong_yeu_cauNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cauColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSo_luong_yeu_cauNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cauColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSo_luong_thuc_lanhNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSo_luong_thuc_lanhNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDon_giaNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Don_giaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDon_giaNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Don_giaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsThanh_tienNull() {
                return this.IsNull(this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tienColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetThanh_tienNull() {
                this[this.tableChi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tienColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class Phieu_Nhap_KhoRow : global::System.Data.DataRow {
            
            private Phieu_Nhap_KhoDataTable tablePhieu_Nhap_Kho;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal Phieu_Nhap_KhoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePhieu_Nhap_Kho = ((Phieu_Nhap_KhoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ten_kho {
                get {
                    try {
                        return ((string)(this[this.tablePhieu_Nhap_Kho.Ten_khoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ten_kho\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.Ten_khoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Ngay_lap {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablePhieu_Nhap_Kho.Ngay_lapColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ngay_lap\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.Ngay_lapColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Ly_do {
                get {
                    try {
                        return ((string)(this[this.tablePhieu_Nhap_Kho.Ly_doColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ly_do\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.Ly_doColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string So_hoa_don {
                get {
                    try {
                        return ((string)(this[this.tablePhieu_Nhap_Kho.So_hoa_donColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'So_hoa_don\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.So_hoa_donColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cong_trinh {
                get {
                    try {
                        return ((string)(this[this.tablePhieu_Nhap_Kho.Cong_trinhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cong_trinh\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.Cong_trinhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Dia_Chi {
                get {
                    try {
                        return ((string)(this[this.tablePhieu_Nhap_Kho.Dia_ChiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Dia_Chi\' in table \'Phieu_Nhap_Kho\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePhieu_Nhap_Kho.Dia_ChiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTen_khoNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.Ten_khoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTen_khoNull() {
                this[this.tablePhieu_Nhap_Kho.Ten_khoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNgay_lapNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.Ngay_lapColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNgay_lapNull() {
                this[this.tablePhieu_Nhap_Kho.Ngay_lapColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLy_doNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.Ly_doColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLy_doNull() {
                this[this.tablePhieu_Nhap_Kho.Ly_doColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSo_hoa_donNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.So_hoa_donColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSo_hoa_donNull() {
                this[this.tablePhieu_Nhap_Kho.So_hoa_donColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCong_trinhNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.Cong_trinhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCong_trinhNull() {
                this[this.tablePhieu_Nhap_Kho.Cong_trinhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDia_ChiNull() {
                return this.IsNull(this.tablePhieu_Nhap_Kho.Dia_ChiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDia_ChiNull() {
                this[this.tablePhieu_Nhap_Kho.Dia_ChiColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent : global::System.EventArgs {
            
            private Chi_Tiet_Phieu_Nhap_Vat_TuRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuRowChangeEvent(Chi_Tiet_Phieu_Nhap_Vat_TuRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Chi_Tiet_Phieu_Nhap_Vat_TuRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class Phieu_Nhap_KhoRowChangeEvent : global::System.EventArgs {
            
            private Phieu_Nhap_KhoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoRowChangeEvent(Phieu_Nhap_KhoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public Phieu_Nhap_KhoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591