//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Phieu_Xuat_Tam
    {
        public int ID_chi_tiet_phieu_xuat_tam { get; set; }
        public string Ma_phieu_xuat_tam { get; set; }
        public string Ma_vat_tu { get; set; }
        public Nullable<int> So_luong_de_nghi { get; set; }
        public Nullable<int> So_luong_thuc_lanh { get; set; }
        public Nullable<bool> Da_duyen_xuat_vat_tu { get; set; }
        public Nullable<int> So_luong_hoan_nhap { get; set; }
        public Nullable<int> So_luong_giu_lai { get; set; }
        public Nullable<bool> Da_duyet_hoan_nhap_giu_lai { get; set; }
        public Nullable<int> So_luong_su_dung { get; set; }
    }
}
