//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Goi_Dau
    {
        public int ID_chi_tiet_GD { get; set; }
        public Nullable<int> ID_VT_Goi_Dau { get; set; }
        public Nullable<decimal> So_luong { get; set; }
        public Nullable<int> ID_ma_phieu { get; set; }
        public Nullable<System.DateTime> Ngay_nhap { get; set; }
    }
}
