//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Phieu_Nhap_Vat_Tu
    {
        public int ID_chi_tiet_phieu_nhap_vat_tu { get; set; }
        public string Ma_phieu_nhap { get; set; }
        public string Ma_vat_tu { get; set; }
        public string Chat_luong { get; set; }
        public Nullable<int> So_luong_yeu_cau { get; set; }
        public Nullable<int> So_luong_thuc_lanh { get; set; }
        public Nullable<int> Don_gia { get; set; }
        public Nullable<int> Thanh_tien { get; set; }
        public Nullable<int> ID_Don_vi_tinh { get; set; }
        public Nullable<bool> Da_duyet { get; set; }
    }
}
