//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiet_kho_muon_vat_tu
    {
        public int ID_chi_tiet_kho_muon_vat_tu { get; set; }
        public Nullable<int> ID_kho_muon_vat_tu { get; set; }
        public string Ma_phieu_xuat_tam { get; set; }
        public Nullable<decimal> SL_muon { get; set; }
        public Nullable<decimal> SL_tra { get; set; }
        public Nullable<decimal> SL_con_no { get; set; }
        public Nullable<System.DateTime> Thoi_gian_cap_nhat { get; set; }
        public string Nguoi_duyet { get; set; }
    }
}
