//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Ton_Kho
    {
        public int ID_Chi_tiet_ton_kho { get; set; }
        public Nullable<int> ID_Ton_kho { get; set; }
        public string Ma_phieu { get; set; }
        public Nullable<int> So_luong { get; set; }
        public Nullable<System.DateTime> Ngay_thay_doi { get; set; }
        public Nullable<bool> Tang_Giam { get; set; }
    
        public virtual Phieu_Nhap_Kho Phieu_Nhap_Kho { get; set; }
        public virtual Phieu_Xuat_Tam_Vat_Tu Phieu_Xuat_Tam_Vat_Tu { get; set; }
        public virtual Ton_kho Ton_kho { get; set; }
    }
}
