//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Don_vi_tinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Don_vi_tinh()
        {
            this.DM_Vat_Tu = new HashSet<DM_Vat_Tu>();
        }
    
        public int ID_Don_vi_tinh { get; set; }
        public string Ten_don_vi_tinh { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_Vat_Tu> DM_Vat_Tu { get; set; }
    }
}
