//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Nhan_Vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_Nhan_Vien()
        {
            this.No_vat_tu = new HashSet<No_vat_tu>();
            this.Phieu_Xuat_Tam_Vat_Tu = new HashSet<Phieu_Xuat_Tam_Vat_Tu>();
        }
    
        public int ID_nhan_vien { get; set; }
        public string Ten_nhan_vien { get; set; }
        public string Ma_nhan_vien { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<No_vat_tu> No_vat_tu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu_Xuat_Tam_Vat_Tu> Phieu_Xuat_Tam_Vat_Tu { get; set; }
    }
}
