//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho_muon_vat_tu
    {
        public int ID { get; set; }
        public Nullable<int> ID_Kho { get; set; }
        public Nullable<int> ID_Kho_muon { get; set; }
        public string Ma_vat_tu { get; set; }
        public Nullable<int> So_luong { get; set; }
        public string Ma_phieu_xuat_tam { get; set; }
    
        public virtual DM_Kho DM_Kho { get; set; }
        public virtual DM_Kho DM_Kho1 { get; set; }
    }
}
