//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho_phu
    {
        public int ID_kho_phu { get; set; }
        public string So_chung_tu { get; set; }
        public string Ly_do { get; set; }
        public Nullable<System.DateTime> Ngay_nhap { get; set; }
        public string Ten_phieu { get; set; }
        public Nullable<int> ID_kho_chinh { get; set; }
    }
}
