//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ky
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ky()
        {
            this.Vat_Tu_Goi_Dau_Ky = new HashSet<Vat_Tu_Goi_Dau_Ky>();
        }
    
        public int ID_ky { get; set; }
        public string Ten_ky { get; set; }
        public Nullable<System.DateTime> Thoi_gian_bat_dau { get; set; }
        public Nullable<System.DateTime> Thoi_gian_ket_thuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vat_Tu_Goi_Dau_Ky> Vat_Tu_Goi_Dau_Ky { get; set; }
    }
}
