//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKhoDienLucEntities : DbContext
    {
        public QLKhoDienLucEntities()
            : base("name=QLKhoDienLucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_Tiet_Phieu_Nhap_Vat_Tu> Chi_Tiet_Phieu_Nhap_Vat_Tu { get; set; }
        public virtual DbSet<Chi_Tiet_Phieu_Xuat_Tam> Chi_Tiet_Phieu_Xuat_Tam { get; set; }
        public virtual DbSet<Chi_Tiet_Ton_Kho> Chi_Tiet_Ton_Kho { get; set; }
        public virtual DbSet<DM_Don_vi_tinh> DM_Don_vi_tinh { get; set; }
        public virtual DbSet<DM_Kho> DM_Kho { get; set; }
        public virtual DbSet<DM_Nhan_Vien> DM_Nhan_Vien { get; set; }
        public virtual DbSet<DM_Vat_Tu> DM_Vat_Tu { get; set; }
        public virtual DbSet<Kho_muon_vat_tu> Kho_muon_vat_tu { get; set; }
        public virtual DbSet<Ky> Kies { get; set; }
        public virtual DbSet<Loai_Phieu_Nhap> Loai_Phieu_Nhap { get; set; }
        public virtual DbSet<No_vat_tu> No_vat_tu { get; set; }
        public virtual DbSet<Phieu_Nhap_Kho> Phieu_Nhap_Kho { get; set; }
        public virtual DbSet<Phieu_Xuat_Tam_Vat_Tu> Phieu_Xuat_Tam_Vat_Tu { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ton_kho> Ton_kho { get; set; }
        public virtual DbSet<Vat_Tu_Goi_Dau_Ky> Vat_Tu_Goi_Dau_Ky { get; set; }
    }
}
