//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(Inventory.Models.QLKhoDienLucEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsd5130d18cb755bc4fc22759458b5da78f9b484ba13e9bb32cb511af16614ff6f))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySetsd5130d18cb755bc4fc22759458b5da78f9b484ba13e9bb32cb511af16614ff6f : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "d5130d18cb755bc4fc22759458b5da78f9b484ba13e9bb32cb511af16614ff6f"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Nhap_Vat_Tu")
            {
                return GetView0();
            }

            if (extentName == "QLKhoDienLucEntities.Chi_Tiet_Phieu_Nhap_Vat_Tu")
            {
                return GetView1();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Chi_Tiet_Ton_Kho")
            {
                return GetView2();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.DM_Kho")
            {
                return GetView3();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.DM_Nhan_Vien")
            {
                return GetView4();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Kho_muon_vat_tu")
            {
                return GetView5();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.No_vat_tu")
            {
                return GetView6();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Phieu_Xuat_Tam_Vat_Tu")
            {
                return GetView7();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Ton_kho")
            {
                return GetView8();
            }

            if (extentName == "QLKhoDienLucEntities.Chi_Tiet_Ton_Kho")
            {
                return GetView9();
            }

            if (extentName == "QLKhoDienLucEntities.DM_Kho")
            {
                return GetView10();
            }

            if (extentName == "QLKhoDienLucEntities.DM_Nhan_Vien")
            {
                return GetView11();
            }

            if (extentName == "QLKhoDienLucEntities.Kho_muon_vat_tu")
            {
                return GetView12();
            }

            if (extentName == "QLKhoDienLucEntities.No_vat_tu")
            {
                return GetView13();
            }

            if (extentName == "QLKhoDienLucEntities.Phieu_Xuat_Tam_Vat_Tu")
            {
                return GetView14();
            }

            if (extentName == "QLKhoDienLucEntities.Ton_kho")
            {
                return GetView15();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.DM_Don_vi_tinh")
            {
                return GetView16();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.DM_Vat_Tu")
            {
                return GetView17();
            }

            if (extentName == "QLKhoDienLucEntities.DM_Don_vi_tinh")
            {
                return GetView18();
            }

            if (extentName == "QLKhoDienLucEntities.DM_Vat_Tu")
            {
                return GetView19();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Ky")
            {
                return GetView20();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Vat_Tu_Goi_Dau_Ky")
            {
                return GetView21();
            }

            if (extentName == "QLKhoDienLucEntities.Kies")
            {
                return GetView22();
            }

            if (extentName == "QLKhoDienLucEntities.Vat_Tu_Goi_Dau_Ky")
            {
                return GetView23();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Loai_Phieu_Nhap")
            {
                return GetView24();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Phieu_Nhap_Kho")
            {
                return GetView25();
            }

            if (extentName == "QLKhoDienLucEntities.Loai_Phieu_Nhap")
            {
                return GetView26();
            }

            if (extentName == "QLKhoDienLucEntities.Phieu_Nhap_Kho")
            {
                return GetView27();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.sysdiagrams")
            {
                return GetView28();
            }

            if (extentName == "QLKhoDienLucEntities.sysdiagrams")
            {
                return GetView29();
            }

            if (extentName == "QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Xuat_Tam")
            {
                return GetView30();
            }

            if (extentName == "QLKhoDienLucEntities.Chi_Tiet_Phieu_Xuat_Tam")
            {
                return GetView31();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Nhap_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Phieu_Nhap_Vat_Tu
        [QLKhoDienLucModel.Store.Chi_Tiet_Phieu_Nhap_Vat_Tu](T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_chi_tiet_phieu_nhap_vat_tu], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_phieu_nhap], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tu], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luong], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cau], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanh], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Don_gia], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tien], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_Don_vi_tinh], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Da_duyet])
    FROM (
        SELECT 
            T.ID_chi_tiet_phieu_nhap_vat_tu AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_chi_tiet_phieu_nhap_vat_tu], 
            T.Ma_phieu_nhap AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_phieu_nhap], 
            T.Ma_vat_tu AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tu], 
            T.Chat_luong AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luong], 
            T.So_luong_yeu_cau AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cau], 
            T.So_luong_thuc_lanh AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanh], 
            T.Don_gia AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Don_gia], 
            T.Thanh_tien AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tien], 
            T.ID_Don_vi_tinh AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_Don_vi_tinh], 
            T.Da_duyet AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Da_duyet], 
            True AS _from0
        FROM QLKhoDienLucEntities.Chi_Tiet_Phieu_Nhap_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Chi_Tiet_Phieu_Nhap_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Phieu_Nhap_Vat_Tu
        [QLKhoDienLucModel.Chi_Tiet_Phieu_Nhap_Vat_Tu](T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_chi_tiet_phieu_nhap_vat_tu], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_phieu_nhap], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tu], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luong], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cau], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanh], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Don_gia], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tien], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_Don_vi_tinh], T1.[Chi_Tiet_Phieu_Nhap_Vat_Tu.Da_duyet])
    FROM (
        SELECT 
            T.ID_chi_tiet_phieu_nhap_vat_tu AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_chi_tiet_phieu_nhap_vat_tu], 
            T.Ma_phieu_nhap AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_phieu_nhap], 
            T.Ma_vat_tu AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Ma_vat_tu], 
            T.Chat_luong AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Chat_luong], 
            T.So_luong_yeu_cau AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_yeu_cau], 
            T.So_luong_thuc_lanh AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.So_luong_thuc_lanh], 
            T.Don_gia AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Don_gia], 
            T.Thanh_tien AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Thanh_tien], 
            T.ID_Don_vi_tinh AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.ID_Don_vi_tinh], 
            T.Da_duyet AS [Chi_Tiet_Phieu_Nhap_Vat_Tu.Da_duyet], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Nhap_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Chi_Tiet_Ton_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Ton_Kho
        [QLKhoDienLucModel.Store.Chi_Tiet_Ton_Kho](T1.[Chi_Tiet_Ton_Kho.ID_Chi_tiet_ton_kho], T1.[Chi_Tiet_Ton_Kho.ID_Ton_kho], T1.[Chi_Tiet_Ton_Kho.Ma_phieu], T1.[Chi_Tiet_Ton_Kho.So_luong], T1.[Chi_Tiet_Ton_Kho.Ngay_thay_doi], T1.[Chi_Tiet_Ton_Kho.Tang_Giam])
    FROM (
        SELECT 
            T.ID_Chi_tiet_ton_kho AS [Chi_Tiet_Ton_Kho.ID_Chi_tiet_ton_kho], 
            T.ID_Ton_kho AS [Chi_Tiet_Ton_Kho.ID_Ton_kho], 
            T.Ma_phieu AS [Chi_Tiet_Ton_Kho.Ma_phieu], 
            T.So_luong AS [Chi_Tiet_Ton_Kho.So_luong], 
            T.Ngay_thay_doi AS [Chi_Tiet_Ton_Kho.Ngay_thay_doi], 
            T.Tang_Giam AS [Chi_Tiet_Ton_Kho.Tang_Giam], 
            True AS _from0
        FROM QLKhoDienLucEntities.Chi_Tiet_Ton_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.DM_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Kho
        [QLKhoDienLucModel.Store.DM_Kho](T1.[DM_Kho.ID_kho], T1.[DM_Kho.Ten_kho], T1.[DM_Kho.Trang_thai])
    FROM (
        SELECT 
            T.ID_kho AS [DM_Kho.ID_kho], 
            T.Ten_kho AS [DM_Kho.Ten_kho], 
            T.Trang_thai AS [DM_Kho.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucEntities.DM_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.DM_Nhan_Vien.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Nhan_Vien
        [QLKhoDienLucModel.Store.DM_Nhan_Vien](T1.[DM_Nhan_Vien.ID_nhan_vien], T1.[DM_Nhan_Vien.Ten_nhan_vien], T1.[DM_Nhan_Vien.Ma_nhan_vien], T1.[DM_Nhan_Vien.Trang_thai])
    FROM (
        SELECT 
            T.ID_nhan_vien AS [DM_Nhan_Vien.ID_nhan_vien], 
            T.Ten_nhan_vien AS [DM_Nhan_Vien.Ten_nhan_vien], 
            T.Ma_nhan_vien AS [DM_Nhan_Vien.Ma_nhan_vien], 
            T.Trang_thai AS [DM_Nhan_Vien.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucEntities.DM_Nhan_Vien AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Kho_muon_vat_tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Kho_muon_vat_tu
        [QLKhoDienLucModel.Store.Kho_muon_vat_tu](T1.[Kho_muon_vat_tu.ID], T1.[Kho_muon_vat_tu.ID_Kho], T1.[Kho_muon_vat_tu.ID_Kho_muon], T1.[Kho_muon_vat_tu.Ma_vat_tu], T1.[Kho_muon_vat_tu.So_luong], T1.[Kho_muon_vat_tu.Ma_phieu_xuat_tam])
    FROM (
        SELECT 
            T.ID AS [Kho_muon_vat_tu.ID], 
            T.ID_Kho AS [Kho_muon_vat_tu.ID_Kho], 
            T.ID_Kho_muon AS [Kho_muon_vat_tu.ID_Kho_muon], 
            T.Ma_vat_tu AS [Kho_muon_vat_tu.Ma_vat_tu], 
            T.So_luong AS [Kho_muon_vat_tu.So_luong], 
            T.Ma_phieu_xuat_tam AS [Kho_muon_vat_tu.Ma_phieu_xuat_tam], 
            True AS _from0
        FROM QLKhoDienLucEntities.Kho_muon_vat_tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.No_vat_tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing No_vat_tu
        [QLKhoDienLucModel.Store.No_vat_tu](T1.[No_vat_tu.ID_No_vat_tu], T1.[No_vat_tu.ID_nhan_vien], T1.[No_vat_tu.Ma_phieu_xuat_tam], T1.[No_vat_tu.Ma_vat_tu], T1.[No_vat_tu.So_luong_giu_lai], T1.[No_vat_tu.Da_tra])
    FROM (
        SELECT 
            T.ID_No_vat_tu AS [No_vat_tu.ID_No_vat_tu], 
            T.ID_nhan_vien AS [No_vat_tu.ID_nhan_vien], 
            T.Ma_phieu_xuat_tam AS [No_vat_tu.Ma_phieu_xuat_tam], 
            T.Ma_vat_tu AS [No_vat_tu.Ma_vat_tu], 
            T.So_luong_giu_lai AS [No_vat_tu.So_luong_giu_lai], 
            T.Da_tra AS [No_vat_tu.Da_tra], 
            True AS _from0
        FROM QLKhoDienLucEntities.No_vat_tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Phieu_Xuat_Tam_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Phieu_Xuat_Tam_Vat_Tu
        [QLKhoDienLucModel.Store.Phieu_Xuat_Tam_Vat_Tu](T1.[Phieu_Xuat_Tam_Vat_Tu.Ma_phieu_xuat_tam], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_nhan_vien], T1.[Phieu_Xuat_Tam_Vat_Tu.Ngay_xuat], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_kho], T1.[Phieu_Xuat_Tam_Vat_Tu.Ly_do], T1.[Phieu_Xuat_Tam_Vat_Tu.Cong_trinh], T1.[Phieu_Xuat_Tam_Vat_Tu.Dia_chi], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_phieu_xuat_tam])
    FROM (
        SELECT 
            T.Ma_phieu_xuat_tam AS [Phieu_Xuat_Tam_Vat_Tu.Ma_phieu_xuat_tam], 
            T.ID_nhan_vien AS [Phieu_Xuat_Tam_Vat_Tu.ID_nhan_vien], 
            T.Ngay_xuat AS [Phieu_Xuat_Tam_Vat_Tu.Ngay_xuat], 
            T.ID_kho AS [Phieu_Xuat_Tam_Vat_Tu.ID_kho], 
            T.Ly_do AS [Phieu_Xuat_Tam_Vat_Tu.Ly_do], 
            T.Cong_trinh AS [Phieu_Xuat_Tam_Vat_Tu.Cong_trinh], 
            T.Dia_chi AS [Phieu_Xuat_Tam_Vat_Tu.Dia_chi], 
            T.ID_phieu_xuat_tam AS [Phieu_Xuat_Tam_Vat_Tu.ID_phieu_xuat_tam], 
            True AS _from0
        FROM QLKhoDienLucEntities.Phieu_Xuat_Tam_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Ton_kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Ton_kho
        [QLKhoDienLucModel.Store.Ton_kho](T1.[Ton_kho.ID_ton_kho], T1.[Ton_kho.ID_kho], T1.[Ton_kho.Ma_vat_tu], T1.[Ton_kho.So_luong])
    FROM (
        SELECT 
            T.ID_ton_kho AS [Ton_kho.ID_ton_kho], 
            T.ID_kho AS [Ton_kho.ID_kho], 
            T.Ma_vat_tu AS [Ton_kho.Ma_vat_tu], 
            T.So_luong AS [Ton_kho.So_luong], 
            True AS _from0
        FROM QLKhoDienLucEntities.Ton_kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Chi_Tiet_Ton_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Ton_Kho
        [QLKhoDienLucModel.Chi_Tiet_Ton_Kho](T1.[Chi_Tiet_Ton_Kho.ID_Chi_tiet_ton_kho], T1.[Chi_Tiet_Ton_Kho.ID_Ton_kho], T1.[Chi_Tiet_Ton_Kho.Ma_phieu], T1.[Chi_Tiet_Ton_Kho.So_luong], T1.[Chi_Tiet_Ton_Kho.Ngay_thay_doi], T1.[Chi_Tiet_Ton_Kho.Tang_Giam])
    FROM (
        SELECT 
            T.ID_Chi_tiet_ton_kho AS [Chi_Tiet_Ton_Kho.ID_Chi_tiet_ton_kho], 
            T.ID_Ton_kho AS [Chi_Tiet_Ton_Kho.ID_Ton_kho], 
            T.Ma_phieu AS [Chi_Tiet_Ton_Kho.Ma_phieu], 
            T.So_luong AS [Chi_Tiet_Ton_Kho.So_luong], 
            T.Ngay_thay_doi AS [Chi_Tiet_Ton_Kho.Ngay_thay_doi], 
            T.Tang_Giam AS [Chi_Tiet_Ton_Kho.Tang_Giam], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Chi_Tiet_Ton_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.DM_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Kho
        [QLKhoDienLucModel.DM_Kho](T1.[DM_Kho.ID_kho], T1.[DM_Kho.Ten_kho], T1.[DM_Kho.Trang_thai])
    FROM (
        SELECT 
            T.ID_kho AS [DM_Kho.ID_kho], 
            T.Ten_kho AS [DM_Kho.Ten_kho], 
            T.Trang_thai AS [DM_Kho.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.DM_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.DM_Nhan_Vien.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Nhan_Vien
        [QLKhoDienLucModel.DM_Nhan_Vien](T1.[DM_Nhan_Vien.ID_nhan_vien], T1.[DM_Nhan_Vien.Ten_nhan_vien], T1.[DM_Nhan_Vien.Ma_nhan_vien], T1.[DM_Nhan_Vien.Trang_thai])
    FROM (
        SELECT 
            T.ID_nhan_vien AS [DM_Nhan_Vien.ID_nhan_vien], 
            T.Ten_nhan_vien AS [DM_Nhan_Vien.Ten_nhan_vien], 
            T.Ma_nhan_vien AS [DM_Nhan_Vien.Ma_nhan_vien], 
            T.Trang_thai AS [DM_Nhan_Vien.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.DM_Nhan_Vien AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Kho_muon_vat_tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Kho_muon_vat_tu
        [QLKhoDienLucModel.Kho_muon_vat_tu](T1.[Kho_muon_vat_tu.ID], T1.[Kho_muon_vat_tu.ID_Kho], T1.[Kho_muon_vat_tu.ID_Kho_muon], T1.[Kho_muon_vat_tu.Ma_vat_tu], T1.[Kho_muon_vat_tu.So_luong], T1.[Kho_muon_vat_tu.Ma_phieu_xuat_tam])
    FROM (
        SELECT 
            T.ID AS [Kho_muon_vat_tu.ID], 
            T.ID_Kho AS [Kho_muon_vat_tu.ID_Kho], 
            T.ID_Kho_muon AS [Kho_muon_vat_tu.ID_Kho_muon], 
            T.Ma_vat_tu AS [Kho_muon_vat_tu.Ma_vat_tu], 
            T.So_luong AS [Kho_muon_vat_tu.So_luong], 
            T.Ma_phieu_xuat_tam AS [Kho_muon_vat_tu.Ma_phieu_xuat_tam], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Kho_muon_vat_tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.No_vat_tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing No_vat_tu
        [QLKhoDienLucModel.No_vat_tu](T1.[No_vat_tu.ID_No_vat_tu], T1.[No_vat_tu.ID_nhan_vien], T1.[No_vat_tu.Ma_phieu_xuat_tam], T1.[No_vat_tu.Ma_vat_tu], T1.[No_vat_tu.So_luong_giu_lai], T1.[No_vat_tu.Da_tra])
    FROM (
        SELECT 
            T.ID_No_vat_tu AS [No_vat_tu.ID_No_vat_tu], 
            T.ID_nhan_vien AS [No_vat_tu.ID_nhan_vien], 
            T.Ma_phieu_xuat_tam AS [No_vat_tu.Ma_phieu_xuat_tam], 
            T.Ma_vat_tu AS [No_vat_tu.Ma_vat_tu], 
            T.So_luong_giu_lai AS [No_vat_tu.So_luong_giu_lai], 
            T.Da_tra AS [No_vat_tu.Da_tra], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.No_vat_tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Phieu_Xuat_Tam_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Phieu_Xuat_Tam_Vat_Tu
        [QLKhoDienLucModel.Phieu_Xuat_Tam_Vat_Tu](T1.[Phieu_Xuat_Tam_Vat_Tu.Ma_phieu_xuat_tam], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_nhan_vien], T1.[Phieu_Xuat_Tam_Vat_Tu.Ngay_xuat], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_kho], T1.[Phieu_Xuat_Tam_Vat_Tu.Ly_do], T1.[Phieu_Xuat_Tam_Vat_Tu.Cong_trinh], T1.[Phieu_Xuat_Tam_Vat_Tu.Dia_chi], T1.[Phieu_Xuat_Tam_Vat_Tu.ID_phieu_xuat_tam])
    FROM (
        SELECT 
            T.Ma_phieu_xuat_tam AS [Phieu_Xuat_Tam_Vat_Tu.Ma_phieu_xuat_tam], 
            T.ID_nhan_vien AS [Phieu_Xuat_Tam_Vat_Tu.ID_nhan_vien], 
            T.Ngay_xuat AS [Phieu_Xuat_Tam_Vat_Tu.Ngay_xuat], 
            T.ID_kho AS [Phieu_Xuat_Tam_Vat_Tu.ID_kho], 
            T.Ly_do AS [Phieu_Xuat_Tam_Vat_Tu.Ly_do], 
            T.Cong_trinh AS [Phieu_Xuat_Tam_Vat_Tu.Cong_trinh], 
            T.Dia_chi AS [Phieu_Xuat_Tam_Vat_Tu.Dia_chi], 
            T.ID_phieu_xuat_tam AS [Phieu_Xuat_Tam_Vat_Tu.ID_phieu_xuat_tam], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Phieu_Xuat_Tam_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Ton_kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Ton_kho
        [QLKhoDienLucModel.Ton_kho](T1.[Ton_kho.ID_ton_kho], T1.[Ton_kho.ID_kho], T1.[Ton_kho.Ma_vat_tu], T1.[Ton_kho.So_luong])
    FROM (
        SELECT 
            T.ID_ton_kho AS [Ton_kho.ID_ton_kho], 
            T.ID_kho AS [Ton_kho.ID_kho], 
            T.Ma_vat_tu AS [Ton_kho.Ma_vat_tu], 
            T.So_luong AS [Ton_kho.So_luong], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Ton_kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.DM_Don_vi_tinh.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Don_vi_tinh
        [QLKhoDienLucModel.Store.DM_Don_vi_tinh](T1.[DM_Don_vi_tinh.ID_Don_vi_tinh], T1.[DM_Don_vi_tinh.Ten_don_vi_tinh], T1.[DM_Don_vi_tinh.Trang_thai])
    FROM (
        SELECT 
            T.ID_Don_vi_tinh AS [DM_Don_vi_tinh.ID_Don_vi_tinh], 
            T.Ten_don_vi_tinh AS [DM_Don_vi_tinh.Ten_don_vi_tinh], 
            T.Trang_thai AS [DM_Don_vi_tinh.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucEntities.DM_Don_vi_tinh AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.DM_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Vat_Tu
        [QLKhoDienLucModel.Store.DM_Vat_Tu](T1.[DM_Vat_Tu.Ten_vat_tu], T1.[DM_Vat_Tu.Ma_vat_tu], T1.[DM_Vat_Tu.ID_Don_vi_tinh], T1.[DM_Vat_Tu.Mo_ta], T1.[DM_Vat_Tu.Trang_thai], T1.[DM_Vat_Tu.Don_gia], T1.[DM_Vat_Tu.Da_xuat], T1.[DM_Vat_Tu.ID_Vat_tu], T1.[DM_Vat_Tu.Ten_khong_dau])
    FROM (
        SELECT 
            T.Ten_vat_tu AS [DM_Vat_Tu.Ten_vat_tu], 
            T.Ma_vat_tu AS [DM_Vat_Tu.Ma_vat_tu], 
            T.ID_Don_vi_tinh AS [DM_Vat_Tu.ID_Don_vi_tinh], 
            T.Mo_ta AS [DM_Vat_Tu.Mo_ta], 
            T.Trang_thai AS [DM_Vat_Tu.Trang_thai], 
            T.Don_gia AS [DM_Vat_Tu.Don_gia], 
            T.Da_xuat AS [DM_Vat_Tu.Da_xuat], 
            T.ID_Vat_tu AS [DM_Vat_Tu.ID_Vat_tu], 
            T.Ten_khong_dau AS [DM_Vat_Tu.Ten_khong_dau], 
            True AS _from0
        FROM QLKhoDienLucEntities.DM_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.DM_Don_vi_tinh.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Don_vi_tinh
        [QLKhoDienLucModel.DM_Don_vi_tinh](T1.[DM_Don_vi_tinh.ID_Don_vi_tinh], T1.[DM_Don_vi_tinh.Ten_don_vi_tinh], T1.[DM_Don_vi_tinh.Trang_thai])
    FROM (
        SELECT 
            T.ID_Don_vi_tinh AS [DM_Don_vi_tinh.ID_Don_vi_tinh], 
            T.Ten_don_vi_tinh AS [DM_Don_vi_tinh.Ten_don_vi_tinh], 
            T.Trang_thai AS [DM_Don_vi_tinh.Trang_thai], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.DM_Don_vi_tinh AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.DM_Vat_Tu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DM_Vat_Tu
        [QLKhoDienLucModel.DM_Vat_Tu](T1.[DM_Vat_Tu.Ten_vat_tu], T1.[DM_Vat_Tu.Ma_vat_tu], T1.[DM_Vat_Tu.ID_Don_vi_tinh], T1.[DM_Vat_Tu.Mo_ta], T1.[DM_Vat_Tu.Trang_thai], T1.[DM_Vat_Tu.Don_gia], T1.[DM_Vat_Tu.Da_xuat], T1.[DM_Vat_Tu.ID_Vat_tu], T1.[DM_Vat_Tu.Ten_khong_dau])
    FROM (
        SELECT 
            T.Ten_vat_tu AS [DM_Vat_Tu.Ten_vat_tu], 
            T.Ma_vat_tu AS [DM_Vat_Tu.Ma_vat_tu], 
            T.ID_Don_vi_tinh AS [DM_Vat_Tu.ID_Don_vi_tinh], 
            T.Mo_ta AS [DM_Vat_Tu.Mo_ta], 
            T.Trang_thai AS [DM_Vat_Tu.Trang_thai], 
            T.Don_gia AS [DM_Vat_Tu.Don_gia], 
            T.Da_xuat AS [DM_Vat_Tu.Da_xuat], 
            T.ID_Vat_tu AS [DM_Vat_Tu.ID_Vat_tu], 
            T.Ten_khong_dau AS [DM_Vat_Tu.Ten_khong_dau], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.DM_Vat_Tu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Ky.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Ky
        [QLKhoDienLucModel.Store.Ky](T1.[Ky.ID_ky], T1.[Ky.Ten_ky], T1.[Ky.Thoi_gian_bat_dau], T1.[Ky.Thoi_gian_ket_thuc])
    FROM (
        SELECT 
            T.ID_ky AS [Ky.ID_ky], 
            T.Ten_ky AS [Ky.Ten_ky], 
            T.Thoi_gian_bat_dau AS [Ky.Thoi_gian_bat_dau], 
            T.Thoi_gian_ket_thuc AS [Ky.Thoi_gian_ket_thuc], 
            True AS _from0
        FROM QLKhoDienLucEntities.Kies AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Vat_Tu_Goi_Dau_Ky.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Vat_Tu_Goi_Dau_Ky
        [QLKhoDienLucModel.Store.Vat_Tu_Goi_Dau_Ky](T1.[Vat_Tu_Goi_Dau_Ky.ID_VT_Goi_Dau], T1.[Vat_Tu_Goi_Dau_Ky.Ma_vat_tu], T1.[Vat_Tu_Goi_Dau_Ky.So_Luong], T1.[Vat_Tu_Goi_Dau_Ky.ID_ky])
    FROM (
        SELECT 
            T.ID_VT_Goi_Dau AS [Vat_Tu_Goi_Dau_Ky.ID_VT_Goi_Dau], 
            T.Ma_vat_tu AS [Vat_Tu_Goi_Dau_Ky.Ma_vat_tu], 
            T.So_Luong AS [Vat_Tu_Goi_Dau_Ky.So_Luong], 
            T.ID_ky AS [Vat_Tu_Goi_Dau_Ky.ID_ky], 
            True AS _from0
        FROM QLKhoDienLucEntities.Vat_Tu_Goi_Dau_Ky AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Kies.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Kies
        [QLKhoDienLucModel.Ky](T1.[Ky.ID_ky], T1.[Ky.Ten_ky], T1.[Ky.Thoi_gian_bat_dau], T1.[Ky.Thoi_gian_ket_thuc])
    FROM (
        SELECT 
            T.ID_ky AS [Ky.ID_ky], 
            T.Ten_ky AS [Ky.Ten_ky], 
            T.Thoi_gian_bat_dau AS [Ky.Thoi_gian_bat_dau], 
            T.Thoi_gian_ket_thuc AS [Ky.Thoi_gian_ket_thuc], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Ky AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Vat_Tu_Goi_Dau_Ky.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Vat_Tu_Goi_Dau_Ky
        [QLKhoDienLucModel.Vat_Tu_Goi_Dau_Ky](T1.[Vat_Tu_Goi_Dau_Ky.ID_VT_Goi_Dau], T1.[Vat_Tu_Goi_Dau_Ky.Ma_vat_tu], T1.[Vat_Tu_Goi_Dau_Ky.So_Luong], T1.[Vat_Tu_Goi_Dau_Ky.ID_ky])
    FROM (
        SELECT 
            T.ID_VT_Goi_Dau AS [Vat_Tu_Goi_Dau_Ky.ID_VT_Goi_Dau], 
            T.Ma_vat_tu AS [Vat_Tu_Goi_Dau_Ky.Ma_vat_tu], 
            T.So_Luong AS [Vat_Tu_Goi_Dau_Ky.So_Luong], 
            T.ID_ky AS [Vat_Tu_Goi_Dau_Ky.ID_ky], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Vat_Tu_Goi_Dau_Ky AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Loai_Phieu_Nhap.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Loai_Phieu_Nhap
        [QLKhoDienLucModel.Store.Loai_Phieu_Nhap](T1.[Loai_Phieu_Nhap.ID_Loai_Phieu_Nhap], T1.[Loai_Phieu_Nhap.Ma_loai_phieu_nhap], T1.[Loai_Phieu_Nhap.Ten_loai_phieu_nhap])
    FROM (
        SELECT 
            T.ID_Loai_Phieu_Nhap AS [Loai_Phieu_Nhap.ID_Loai_Phieu_Nhap], 
            T.Ma_loai_phieu_nhap AS [Loai_Phieu_Nhap.Ma_loai_phieu_nhap], 
            T.Ten_loai_phieu_nhap AS [Loai_Phieu_Nhap.Ten_loai_phieu_nhap], 
            True AS _from0
        FROM QLKhoDienLucEntities.Loai_Phieu_Nhap AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Phieu_Nhap_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Phieu_Nhap_Kho
        [QLKhoDienLucModel.Store.Phieu_Nhap_Kho](T1.[Phieu_Nhap_Kho.Ma_phieu_nhap], T1.[Phieu_Nhap_Kho.Kho_nhan], T1.[Phieu_Nhap_Kho.Ngay_lap], T1.[Phieu_Nhap_Kho.Ly_do], T1.[Phieu_Nhap_Kho.So_hoa_don], T1.[Phieu_Nhap_Kho.Cong_trinh], T1.[Phieu_Nhap_Kho.Dia_Chi], T1.[Phieu_Nhap_Kho.ID_Loai_Phieu_Nhap], T1.[Phieu_Nhap_Kho.Kho_xuat_ra], T1.[Phieu_Nhap_Kho.Da_phan_kho], T1.[Phieu_Nhap_Kho.ID_phieu_nhap])
    FROM (
        SELECT 
            T.Ma_phieu_nhap AS [Phieu_Nhap_Kho.Ma_phieu_nhap], 
            T.Kho_nhan AS [Phieu_Nhap_Kho.Kho_nhan], 
            T.Ngay_lap AS [Phieu_Nhap_Kho.Ngay_lap], 
            T.Ly_do AS [Phieu_Nhap_Kho.Ly_do], 
            T.So_hoa_don AS [Phieu_Nhap_Kho.So_hoa_don], 
            T.Cong_trinh AS [Phieu_Nhap_Kho.Cong_trinh], 
            T.Dia_Chi AS [Phieu_Nhap_Kho.Dia_Chi], 
            T.ID_Loai_Phieu_Nhap AS [Phieu_Nhap_Kho.ID_Loai_Phieu_Nhap], 
            T.Kho_xuat_ra AS [Phieu_Nhap_Kho.Kho_xuat_ra], 
            T.Da_phan_kho AS [Phieu_Nhap_Kho.Da_phan_kho], 
            T.ID_phieu_nhap AS [Phieu_Nhap_Kho.ID_phieu_nhap], 
            True AS _from0
        FROM QLKhoDienLucEntities.Phieu_Nhap_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Loai_Phieu_Nhap.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Loai_Phieu_Nhap
        [QLKhoDienLucModel.Loai_Phieu_Nhap](T1.[Loai_Phieu_Nhap.ID_Loai_Phieu_Nhap], T1.[Loai_Phieu_Nhap.Ma_loai_phieu_nhap], T1.[Loai_Phieu_Nhap.Ten_loai_phieu_nhap])
    FROM (
        SELECT 
            T.ID_Loai_Phieu_Nhap AS [Loai_Phieu_Nhap.ID_Loai_Phieu_Nhap], 
            T.Ma_loai_phieu_nhap AS [Loai_Phieu_Nhap.Ma_loai_phieu_nhap], 
            T.Ten_loai_phieu_nhap AS [Loai_Phieu_Nhap.Ten_loai_phieu_nhap], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Loai_Phieu_Nhap AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Phieu_Nhap_Kho.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Phieu_Nhap_Kho
        [QLKhoDienLucModel.Phieu_Nhap_Kho](T1.[Phieu_Nhap_Kho.Ma_phieu_nhap], T1.[Phieu_Nhap_Kho.Kho_nhan], T1.[Phieu_Nhap_Kho.Ngay_lap], T1.[Phieu_Nhap_Kho.Ly_do], T1.[Phieu_Nhap_Kho.So_hoa_don], T1.[Phieu_Nhap_Kho.Cong_trinh], T1.[Phieu_Nhap_Kho.Dia_Chi], T1.[Phieu_Nhap_Kho.ID_Loai_Phieu_Nhap], T1.[Phieu_Nhap_Kho.Kho_xuat_ra], T1.[Phieu_Nhap_Kho.Da_phan_kho], T1.[Phieu_Nhap_Kho.ID_phieu_nhap])
    FROM (
        SELECT 
            T.Ma_phieu_nhap AS [Phieu_Nhap_Kho.Ma_phieu_nhap], 
            T.Kho_nhan AS [Phieu_Nhap_Kho.Kho_nhan], 
            T.Ngay_lap AS [Phieu_Nhap_Kho.Ngay_lap], 
            T.Ly_do AS [Phieu_Nhap_Kho.Ly_do], 
            T.So_hoa_don AS [Phieu_Nhap_Kho.So_hoa_don], 
            T.Cong_trinh AS [Phieu_Nhap_Kho.Cong_trinh], 
            T.Dia_Chi AS [Phieu_Nhap_Kho.Dia_Chi], 
            T.ID_Loai_Phieu_Nhap AS [Phieu_Nhap_Kho.ID_Loai_Phieu_Nhap], 
            T.Kho_xuat_ra AS [Phieu_Nhap_Kho.Kho_xuat_ra], 
            T.Da_phan_kho AS [Phieu_Nhap_Kho.Da_phan_kho], 
            T.ID_phieu_nhap AS [Phieu_Nhap_Kho.ID_phieu_nhap], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Phieu_Nhap_Kho AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.sysdiagrams.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing sysdiagrams
        [QLKhoDienLucModel.Store.sysdiagrams](T1.sysdiagrams_name, T1.[sysdiagrams.principal_id], T1.[sysdiagrams.diagram_id], T1.sysdiagrams_version, T1.sysdiagrams_definition)
    FROM (
        SELECT 
            T.name AS sysdiagrams_name, 
            T.principal_id AS [sysdiagrams.principal_id], 
            T.diagram_id AS [sysdiagrams.diagram_id], 
            T.version AS sysdiagrams_version, 
            T.definition AS sysdiagrams_definition, 
            True AS _from0
        FROM QLKhoDienLucEntities.sysdiagrams AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.sysdiagrams.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing sysdiagrams
        [QLKhoDienLucModel.sysdiagram](T1.sysdiagram_name, T1.[sysdiagram.principal_id], T1.[sysdiagram.diagram_id], T1.sysdiagram_version, T1.sysdiagram_definition)
    FROM (
        SELECT 
            T.name AS sysdiagram_name, 
            T.principal_id AS [sysdiagram.principal_id], 
            T.diagram_id AS [sysdiagram.diagram_id], 
            T.version AS sysdiagram_version, 
            T.definition AS sysdiagram_definition, 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.sysdiagrams AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Xuat_Tam.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView30()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Phieu_Xuat_Tam
        [QLKhoDienLucModel.Store.Chi_Tiet_Phieu_Xuat_Tam](T1.[Chi_Tiet_Phieu_Xuat_Tam.ID_chi_tiet_phieu_xuat_tam], T1.[Chi_Tiet_Phieu_Xuat_Tam.Ma_phieu_xuat_tam], T1.[Chi_Tiet_Phieu_Xuat_Tam.Ma_vat_tu], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_de_nghi], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_thuc_xuat], T1.[Chi_Tiet_Phieu_Xuat_Tam.Da_duyen_xuat_vat_tu], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_hoan_nhap], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_giu_lai], T1.[Chi_Tiet_Phieu_Xuat_Tam.Da_duyet_hoan_nhap_giu_lai], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_su_dung])
    FROM (
        SELECT 
            T.ID_chi_tiet_phieu_xuat_tam AS [Chi_Tiet_Phieu_Xuat_Tam.ID_chi_tiet_phieu_xuat_tam], 
            T.Ma_phieu_xuat_tam AS [Chi_Tiet_Phieu_Xuat_Tam.Ma_phieu_xuat_tam], 
            T.Ma_vat_tu AS [Chi_Tiet_Phieu_Xuat_Tam.Ma_vat_tu], 
            T.So_luong_de_nghi AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_de_nghi], 
            T.So_luong_thuc_xuat AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_thuc_xuat], 
            T.Da_duyen_xuat_vat_tu AS [Chi_Tiet_Phieu_Xuat_Tam.Da_duyen_xuat_vat_tu], 
            T.So_luong_hoan_nhap AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_hoan_nhap], 
            T.So_luong_giu_lai AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_giu_lai], 
            T.Da_duyet_hoan_nhap_giu_lai AS [Chi_Tiet_Phieu_Xuat_Tam.Da_duyet_hoan_nhap_giu_lai], 
            T.So_luong_su_dung AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_su_dung], 
            True AS _from0
        FROM QLKhoDienLucEntities.Chi_Tiet_Phieu_Xuat_Tam AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for QLKhoDienLucEntities.Chi_Tiet_Phieu_Xuat_Tam.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView31()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Chi_Tiet_Phieu_Xuat_Tam
        [QLKhoDienLucModel.Chi_Tiet_Phieu_Xuat_Tam](T1.[Chi_Tiet_Phieu_Xuat_Tam.ID_chi_tiet_phieu_xuat_tam], T1.[Chi_Tiet_Phieu_Xuat_Tam.Ma_phieu_xuat_tam], T1.[Chi_Tiet_Phieu_Xuat_Tam.Ma_vat_tu], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_de_nghi], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_thuc_xuat], T1.[Chi_Tiet_Phieu_Xuat_Tam.Da_duyen_xuat_vat_tu], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_hoan_nhap], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_giu_lai], T1.[Chi_Tiet_Phieu_Xuat_Tam.Da_duyet_hoan_nhap_giu_lai], T1.[Chi_Tiet_Phieu_Xuat_Tam.So_luong_su_dung])
    FROM (
        SELECT 
            T.ID_chi_tiet_phieu_xuat_tam AS [Chi_Tiet_Phieu_Xuat_Tam.ID_chi_tiet_phieu_xuat_tam], 
            T.Ma_phieu_xuat_tam AS [Chi_Tiet_Phieu_Xuat_Tam.Ma_phieu_xuat_tam], 
            T.Ma_vat_tu AS [Chi_Tiet_Phieu_Xuat_Tam.Ma_vat_tu], 
            T.So_luong_de_nghi AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_de_nghi], 
            T.So_luong_thuc_xuat AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_thuc_xuat], 
            T.Da_duyen_xuat_vat_tu AS [Chi_Tiet_Phieu_Xuat_Tam.Da_duyen_xuat_vat_tu], 
            T.So_luong_hoan_nhap AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_hoan_nhap], 
            T.So_luong_giu_lai AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_giu_lai], 
            T.Da_duyet_hoan_nhap_giu_lai AS [Chi_Tiet_Phieu_Xuat_Tam.Da_duyet_hoan_nhap_giu_lai], 
            T.So_luong_su_dung AS [Chi_Tiet_Phieu_Xuat_Tam.So_luong_su_dung], 
            True AS _from0
        FROM QLKhoDienLucModelStoreContainer.Chi_Tiet_Phieu_Xuat_Tam AS T
    ) AS T1");
        }
    }
}
