//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class No_vat_tu
    {
        public int ID_No_vat_tu { get; set; }
        public Nullable<int> ID_nhan_vien { get; set; }
        public string Ma_phieu_xuat_tam { get; set; }
        public string Ma_vat_tu { get; set; }
        public Nullable<int> So_luong_giu_lai { get; set; }
        public Nullable<bool> Da_tra { get; set; }
    
        public virtual DM_Nhan_Vien DM_Nhan_Vien { get; set; }
    }
}
