//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu_Xuat_Tam_Vat_Tu
    {
        public string Ma_phieu_xuat_tam { get; set; }
        public Nullable<int> ID_nhan_vien { get; set; }
        public Nullable<System.DateTime> Ngay_xuat { get; set; }
        public Nullable<int> ID_kho { get; set; }
        public string Ly_do { get; set; }
        public string Cong_trinh { get; set; }
        public string Dia_chi { get; set; }
        public int ID_phieu_xuat_tam { get; set; }
    
        public virtual DM_Kho DM_Kho { get; set; }
        public virtual DM_Nhan_Vien DM_Nhan_Vien { get; set; }
    }
}
